---
- hosts: etcd
  remote_user: pirate
  become: true
  vars:
    ARCH: "arm"
    LAST_K8S_VERSION: "$(curl -sSL 'https://storage.googleapis.com/kubernetes-release/release/stable.txt')"
    # see: https://github.com/kubernetes/kubernetes/issues/34702
    K8S_VERSION: "v1.3.6"
    IP_ADDRESS: "$(ip -o -4 addr list $(ip -o -4 route show to default | awk '{print $5}' | head -1) | awk '{print $4}' | cut -d/ -f1 | head -1)"
    KUBELET_MOUNT: "-v /var/lib/kubelet:/var/lib/kubelet:shared"
    KUBELET_MOUNTS: "-v /sys:/sys:rw \
        -v /var/run:/var/run:rw \
        -v /run:/run:rw \
        -v /var/lib/docker:/var/lib/docker:rw \
        {{ KUBELET_MOUNT }} \
        -v /var/log/containers:/var/log/containers:rw"
    CNI_ARGS: ""
    CONTAINERIZED_FLAG: ""
  tasks:
    - name: clean docker k8s master
      shell: docker rm -f kube_kubelet-master; exit 0
    - name: run docker k8s master
      shell: |
        docker run -d \
          --net=host \
          --pid=host \
          --privileged \
          --restart=always \
          --name kube_kubelet-master \
          {{ KUBELET_MOUNTS }} \
          gcr.io/google_containers/hyperkube-{{ ARCH }}:{{ K8S_VERSION }} \
          /hyperkube kubelet \
            --allow-privileged \
            --api-servers=http://localhost:8080 \
            --config=/etc/kubernetes/manifests-multi \
            --cluster-dns=10.0.0.10 \
            --cluster-domain=cluster.local \
            {{ CNI_ARGS }} \
            {{ CONTAINERIZED_FLAG }} \
            --hostname-override={{ IP_ADDRESS }} \
            --v=2
