---
- hosts: kube-masters:kube-workers
  remote_user: pirate
  become: true
  vars:
    BOOTSTRAP_DOCKER_PARAM: "-H unix:///var/run/docker-bootstrap.sock"
    IP_ADDRESS: "$(ip -o -4 addr list $(ip -o -4 route show to default | awk '{print $5}' | head -1) | awk '{print $4}' | cut -d/ -f1 | head -1)"
    etcd_public_ip: "{{ IP_ADDRESS }}"
    ARCH: "arm"
    FLANNEL_VERSION: "v0.6.1"
    FLANNEL_IPMASQ: "true"
    FLANNEL_BACKEND: "udp"
    FLANNEL_NETWORK: "10.1.0.0/16"
    FLANNEL_SUBNET_DIR: "/run/flannel"
  tasks:
    - name: clean docker flannel
      shell: docker {{ BOOTSTRAP_DOCKER_PARAM }} rm -f flannel; exit 0
    - name: run docker flannel
      shell: |
        curl -sSL http://localhost:2379/v2/keys/coreos.com/network/config -XPUT \
          -d value="{ \"Network\": \"{{ FLANNEL_NETWORK }}\", \"Backend\": {\"Type\": \"{{ FLANNEL_BACKEND }}\"}}"
        rm -f {{ FLANNEL_SUBNET_DIR }}/subnet.env
        docker {{ BOOTSTRAP_DOCKER_PARAM }} run -d \
          --name flannel \
          --restart=always \
          --net=host \
          --privileged \
          -v /dev/net:/dev/net \
          -v {{ FLANNEL_SUBNET_DIR }}:{{ FLANNEL_SUBNET_DIR }} \
          quay.io/coreos/flannel:{{ FLANNEL_VERSION }}-{{ ARCH }} \
          /opt/bin/flanneld \
            --etcd-endpoints=http://{{ etcd_public_ip }}:2379 \
            --ip-masq="{{ FLANNEL_IPMASQ }}" \
            --iface="{{ IP_ADDRESS }}"
    - service:
        name: docker-bootstrap
        state: restarted
    - wait_for:
        path: "{{ FLANNEL_SUBNET_DIR }}/subnet.env"
